name: pre-commit

on:
  pull_request:
  push:
    branches:
    - main
    - develop

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0

  verify-output:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - uses: actions/cache@v2
      with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        sudo apt-get install graphviz
    - name: Verify examples output
      run: make verify-output
